train_dir: dataset-landscape-main/seg_train
image_size: [150, 150]
learning_rate: 0.0001
batch_size: 128
epochs: 3
model_path: landscape_classifier.keras
compressed_model_path: landscape_classifier.tflite